/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { I18nKey, ScoreKey, SupportedLanguages } from "./yahtzee-toolkit";
import { SelectedEvent } from "./components/score-card/score-card";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface YahtzeeDice {
        "locked": boolean;
        "value": number;
    }
    interface YahtzeeDiceContainer {
    }
    interface YahtzeeGameFinished {
    }
    interface YahtzeeHeader {
        "currentLang": SupportedLanguages;
    }
    interface YahtzeeI18n {
        "i18n": I18nKey;
    }
    interface YahtzeeNoGame {
    }
    interface YahtzeeScoreCard {
        "diceValue": number;
        "displayDiceValue": boolean;
        "scoreKey": ScoreKey;
        "value": number;
    }
    interface YahtzeeScoreContainer {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLYahtzeeDiceElement extends Components.YahtzeeDice, HTMLStencilElement {
    }
    var HTMLYahtzeeDiceElement: {
        prototype: HTMLYahtzeeDiceElement;
        new (): HTMLYahtzeeDiceElement;
    };
    interface HTMLYahtzeeDiceContainerElement extends Components.YahtzeeDiceContainer, HTMLStencilElement {
    }
    var HTMLYahtzeeDiceContainerElement: {
        prototype: HTMLYahtzeeDiceContainerElement;
        new (): HTMLYahtzeeDiceContainerElement;
    };
    interface HTMLYahtzeeGameFinishedElement extends Components.YahtzeeGameFinished, HTMLStencilElement {
    }
    var HTMLYahtzeeGameFinishedElement: {
        prototype: HTMLYahtzeeGameFinishedElement;
        new (): HTMLYahtzeeGameFinishedElement;
    };
    interface HTMLYahtzeeHeaderElement extends Components.YahtzeeHeader, HTMLStencilElement {
    }
    var HTMLYahtzeeHeaderElement: {
        prototype: HTMLYahtzeeHeaderElement;
        new (): HTMLYahtzeeHeaderElement;
    };
    interface HTMLYahtzeeI18nElement extends Components.YahtzeeI18n, HTMLStencilElement {
    }
    var HTMLYahtzeeI18nElement: {
        prototype: HTMLYahtzeeI18nElement;
        new (): HTMLYahtzeeI18nElement;
    };
    interface HTMLYahtzeeNoGameElement extends Components.YahtzeeNoGame, HTMLStencilElement {
    }
    var HTMLYahtzeeNoGameElement: {
        prototype: HTMLYahtzeeNoGameElement;
        new (): HTMLYahtzeeNoGameElement;
    };
    interface HTMLYahtzeeScoreCardElement extends Components.YahtzeeScoreCard, HTMLStencilElement {
    }
    var HTMLYahtzeeScoreCardElement: {
        prototype: HTMLYahtzeeScoreCardElement;
        new (): HTMLYahtzeeScoreCardElement;
    };
    interface HTMLYahtzeeScoreContainerElement extends Components.YahtzeeScoreContainer, HTMLStencilElement {
    }
    var HTMLYahtzeeScoreContainerElement: {
        prototype: HTMLYahtzeeScoreContainerElement;
        new (): HTMLYahtzeeScoreContainerElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "yahtzee-dice": HTMLYahtzeeDiceElement;
        "yahtzee-dice-container": HTMLYahtzeeDiceContainerElement;
        "yahtzee-game-finished": HTMLYahtzeeGameFinishedElement;
        "yahtzee-header": HTMLYahtzeeHeaderElement;
        "yahtzee-i18n": HTMLYahtzeeI18nElement;
        "yahtzee-no-game": HTMLYahtzeeNoGameElement;
        "yahtzee-score-card": HTMLYahtzeeScoreCardElement;
        "yahtzee-score-container": HTMLYahtzeeScoreContainerElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface YahtzeeDice {
        "locked"?: boolean;
        "value"?: number;
    }
    interface YahtzeeDiceContainer {
    }
    interface YahtzeeGameFinished {
    }
    interface YahtzeeHeader {
        "currentLang"?: SupportedLanguages;
    }
    interface YahtzeeI18n {
        "i18n"?: I18nKey;
    }
    interface YahtzeeNoGame {
    }
    interface YahtzeeScoreCard {
        "diceValue"?: number;
        "displayDiceValue"?: boolean;
        "onSelected"?: (event: CustomEvent<SelectedEvent>) => void;
        "scoreKey"?: ScoreKey;
        "value"?: number;
    }
    interface YahtzeeScoreContainer {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "yahtzee-dice": YahtzeeDice;
        "yahtzee-dice-container": YahtzeeDiceContainer;
        "yahtzee-game-finished": YahtzeeGameFinished;
        "yahtzee-header": YahtzeeHeader;
        "yahtzee-i18n": YahtzeeI18n;
        "yahtzee-no-game": YahtzeeNoGame;
        "yahtzee-score-card": YahtzeeScoreCard;
        "yahtzee-score-container": YahtzeeScoreContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "yahtzee-dice": LocalJSX.YahtzeeDice & JSXBase.HTMLAttributes<HTMLYahtzeeDiceElement>;
            "yahtzee-dice-container": LocalJSX.YahtzeeDiceContainer & JSXBase.HTMLAttributes<HTMLYahtzeeDiceContainerElement>;
            "yahtzee-game-finished": LocalJSX.YahtzeeGameFinished & JSXBase.HTMLAttributes<HTMLYahtzeeGameFinishedElement>;
            "yahtzee-header": LocalJSX.YahtzeeHeader & JSXBase.HTMLAttributes<HTMLYahtzeeHeaderElement>;
            "yahtzee-i18n": LocalJSX.YahtzeeI18n & JSXBase.HTMLAttributes<HTMLYahtzeeI18nElement>;
            "yahtzee-no-game": LocalJSX.YahtzeeNoGame & JSXBase.HTMLAttributes<HTMLYahtzeeNoGameElement>;
            "yahtzee-score-card": LocalJSX.YahtzeeScoreCard & JSXBase.HTMLAttributes<HTMLYahtzeeScoreCardElement>;
            "yahtzee-score-container": LocalJSX.YahtzeeScoreContainer & JSXBase.HTMLAttributes<HTMLYahtzeeScoreContainerElement>;
        }
    }
}
